### ISSUE TITLE
Unnecessary margin around and within Ribbon component

### ISSUE THREAD

**Issue by sibyl229** [geneontology/ribbon#13]
It's better to add margin where the component is **used** rather than including them in the component. I'm correcting for the margin in the AGR repo for now. But might be a good idea to have it fixed here eventually.
![screen shot 2017-05-25 at 12 33 54 pm](https://cloud.githubusercontent.com/assets/1753893/26460168/d35c4434-4146-11e7-8d63-58b6170afee7.png)
![screen shot 2017-05-25 at 12 34 16 pm](https://cloud.githubusercontent.com/assets/1753893/26460169/d35fc03c-4146-11e7-99f6-0c44e94f59b7.png)

**Comment by selewis** [comment]
Agreed (vestigial code). Will try and get this out today.

**Comment by sibyl229** [comment]
Thanks @selewis ! Not really urgent. If you have other priorities, this one isn't necessary for the freeze.

**Comment by selewis** [comment]
Feeling a bit dense. Margins are definitely there, but not sure where they are coming from. Any hints?

**Comment by sibyl229** [comment]
Thanks @lpalbou
