### ISSUE TITLE
separate Ribbon by aspects providing one cell space between them

### ISSUE THREAD

**Issue by judyblake** [geneontology/ribbon#16]
do this instead of having blank cell

**Comment by sabrinatoro** [comment]
Feed back from looking at the AGR gene page (AGR-491 in the AGR Jira): 
It would be nice to see what is Molecular Function, Biological Process, Cellular Component. I am sure there is a lot of ways that can be done.
[note: the following mockup showed a different way to separate the aspects. Providing one cell space between them would work fine]
![agr-491 mf-bp-cc](https://user-images.githubusercontent.com/12737987/28696121-9773ca90-72e8-11e7-9ca7-78378f44b420.jpg)

**Comment by selewis** [comment]
Fixed in next release 0.1.6
