### ISSUE TITLE
New GO-ribbon categories on AGR site

### ISSUE THREAD

**Issue by hdrabkin** [geneontology/ribbon#18]
This is for Judy

After analysis of experimental annotations from AGR MODs
This is a list of the number of gene products assigned to each category for the AGR organisms plus human:
only experimental evidence
includes inferring over regulates relation
NOT excluded
dual taxon excluded
[merged_slim.txt](https://github.com/geneontology/ribbon/files/1116287/merged_slim.txt)

Attached is the file

judy

**Comment by cmungall** [comment]
Why is this being filed here? If the intent is to change the contents of the existing AGR slim, or to make a new slim, this should go on the go-ontology tracker where an ontology editor can make the required modifications

**Comment by hdrabkin** [comment]
Forwarded the email notice to Judy. She told me to put in with the other ribbon tickets. 
 It appears she has no git account?

**Comment by kltm** [comment]
@judyblake is the current one
