### ISSUE TITLE
Handle ND annotations

### ISSUE THREAD

**Issue by selewis** [geneontology/ribbon#52]
Don't want these showing up under "other"

**Comment by nathandunn** [comment]
@selewis  

1. will this be an internal filter (like protein binding)? 
2. - OR - should this need to be filtered upstream in biolink, and if so, does it need a ticket?

**Comment by selewis** [comment]
It will be internal to ribbon, I'm working on the code now myself.

**Comment by selewis** [comment]
@nathandunn - made the fix, take a look please and get it to the alliance.

**Comment by nathandunn** [comment]
It is done.  Let me know if there was a bug I should have linked it to. 

Nathan

**Comment by selewis** [comment]
Thanks, the only bug report was the one I created on the geneontology
ribbon issue tracker as far as I know.

-S
