### ISSUE TITLE
fixes for other / ND boxes

### ISSUE THREAD

**Issue by nathandunn** [geneontology/ribbon#53]
Per https://agr-jira.atlassian.net/browse/AGR-1124

@selewis  I know you had some notes for the fixes on this.   I know part of them, listed here, but I'll let you add the rest.  

Minor typos
- uncaptalize "No known" 
- add "No known location" to cellular component
- add back "other?" (not sure hot this would come in to play filtering)
- add back ND evidence

**Comment by selewis** [comment]
But there is something known for cellular component for that yeast gene. The text only shows up if there is an ND

**Comment by selewis** [comment]
And Other is still there, just as it always was.
