### ISSUE TITLE
make ribbon code more configurable

### ISSUE THREAD

**Issue by nathandunn** [geneontology/ribbon#62]
From https://github.com/alliance-genome/agr_ui/pull/314#issuecomment-424100788 

> Yeah, it's because the ribbon CSS is applying a fixed width and height to those elements, plus padding and a margin. On the alliance site, we have a global box-sizing: border-box CSS rule on all elements. But the ribbon seems to be assuming that box-sizing will be content-box.

> There's nothing we can really do on the alliance site to fix this. We can't just change the box-sizing setting because it would break bootstrap.

> The ribbon code could just set the padding and not have explicit width and heights. If you want those boxes to be the same size you could use flexboxes. Or if all else fails you could just override the box-sizing setting on the necessary elements.

From this error:

<img width="324" alt="screen shot 2018-09-24 at 12 27 58 pm" src="https://user-images.githubusercontent.com/751274/45980383-aaa3d300-c006-11e8-805e-424a28df4ff5.png">

vs 

<img width="948" alt="screen shot 2018-09-24 at 12 22 10 pm" src="https://user-images.githubusercontent.com/751274/45980390-b55e6800-c006-11e8-84eb-2880ffe2959b.png">

When launched within the AGR_UI codebase.

**Comment by nathandunn** [comment]
pinging @lpalbou

**Comment by lpalbou** [comment]
PR here: https://github.com/geneontology/ribbon/pull/64
