### ISSUE TITLE
Support multiple entries

### ISSUE THREAD

**Issue by lpalbou** [geneontology/ribbon#67]
For the moment, the Ribbon is only able to represent the slims for a single entry / Gene Product.

We want it to be able to accept multiple gene products, in order to highlight the differences between them. Two use cases come to mind:
* compare gene products across species
* compare gene products of a same family to see the subtle differences

**Comment by hattrill** [comment]
It would be also very useful to compare any list of genes within a species from a user defined list i.e. upload gene ids/symbols, select species filter 
Or, upload a set generated from a query e.g. D.mel genes annotated with "GO:0007173 epidermal growth factor receptor signaling pathway (exact match)" as it can give the user a quick over-view to hep them find the receptors or enzymes of that pathway, for example.

Inserting the mock-up of the FlyBase ribbon grid spec:
![screen shot 2018-10-02 at 16 32 08](https://user-images.githubusercontent.com/11865746/46359645-904ea280-c661-11e8-99d5-2dbc25de57eb.png)

**Comment by hattrill** [comment]
Also, what we might want to do, if we want to see the differences between species, is be able to select experimental/exclude ISS/IBA annotations to give the user a chance to see the differences between model organisms.

**Comment by nathandunn** [comment]
@hattrill  / @lpalbou  

I wonder, with cross-species if we're starting to emulate (by design, not data) some of what phenogrid does:

https://monarchinitiative.org/analyze/phenotypes?input_items=HP%3A0025085+MP%3A0013304+HP%3A0030663+HP%3A0001300&mode=search&target_species=all&limit=100&gene_list=

![screen shot 2018-10-02 at 8 49 32 am](https://user-images.githubusercontent.com/751274/46360374-1ba74400-c620-11e8-8b84-cc6cfa2bf1df.png)

**Comment by nathandunn** [comment]
(and I chose really bad and unrelated terms)

**Comment by hattrill** [comment]
MGI’s human-mouse: disease connection tool is another example of a matrix presentation of data between species.

![image](https://user-images.githubusercontent.com/11865746/46360616-bbd28c80-c663-11e8-9149-cb896cf8f727.png)

and Gene2Function uses the whole GO slim to compare across orthologous gene sets:

![image](https://user-images.githubusercontent.com/11865746/46360679-d99ff180-c663-11e8-83b3-45462ca59c04.png)

**Comment by hattrill** [comment]
So, yes....emulate/inspired by!
But, it would be really exciting to allow comparison user-generated gene set (with species, cross-species).

**Comment by hattrill** [comment]
The biological process ribbon slim is very high-level, and what may be useful is to produce a suite of slims to help the user look at a deeper comparison:

For example, a "cellular process slim" maight contain the basic cellular functions:
e.g. cell cycle, cell death, growth, division, trafficking, DNA replication, transcription, translation, signal transduction, cytoskeletal organization, autophagy, DNA repair, protein maturation.

(this slim might be useful on a gene page as well, to drill a bit further down to a gene's basic functional grouping - last common ancestor style)

Or a development slim (by its nature, this would be weighted towards multicellular organisms) containing high-level terms relating to various system development, appendage development, pattern specification, tissue growth, etc.

**Comment by hattrill** [comment]
Hi @paaatrick I am tagging you (hopefully the correct person!) as I thought you might be interested - this is very similar to the wonderful orthologs comparision tool for the expression working groups.

**Comment by lpalbou** [comment]
Here is a screenshot for the current Ribbon multi entities that I am working on:
<img width="1498" alt="ribbon multi entities" src="https://user-images.githubusercontent.com/24249870/48634105-b2825280-e979-11e8-89a1-1139120b63d5.png">

@hattrill 
**Interactive exploration of GO classification:** the idea of interactively looking deeper into the GO classification is possible and interesting, we discussed it sometime in GO. However IMHO, when trying to deliver a rapid broad overview of a gene product, as well as to allow its comparison with others, this may rapidly be counterintuitive as we have no common stable reference.

**Evidence Codes:**
Yep, we plan to make the evidence codes global, so it does filter not only the table, but also the ribbons (https://github.com/geneontology/ribbon/issues/68)

**Comment by hattrill** [comment]
@lpalbou This looks very nice, I particularly like the shaping of the aspect-specific all and other cells. 

Is the plan to implement this for just orthologs (like expression, where the user is given a list of predicted orthologs for selction) or would there be a potential to have a user-defined set of genes? I think this would be where our main interest lies - the ability to stack up any set of genes. How many genes is it feasible to compare?

With regard to looking deeper into the GO, I think that this could just be achieved by having a bespoke set of slims - but I can see how this would fall outside the Alliance's aims. As that it not a tooling issue, more a content, that's not an issue for me - we can figure that out if we want to adapt it for FlyBase.

Filtering on evidence codes would be really useful - being able to easily trace experimentally supported annotations for orthologs is key when doing cross-species analysis.

**Comment by lpalbou** [comment]
@hattrill sorry for the delay in my response. This is a general implementation, so you can use that functionality in any given context and with any set of genes. There is no real limitation on how many genes you could add, but the initial loading time will also stack up (fetching more data). 

Example with 10 genes:

<img width="1427" alt="screen shot 2018-11-27 at 3 50 19 am" src="https://user-images.githubusercontent.com/24249870/49080161-97280a80-f1f7-11e8-9400-0f43bebd153b.png">

For 100s of genes, I think some changes would have to be introduced, including data streaming (fetching the full data on a slim, only when needed) and some UI refactoring also (e.g. maximum height of the ribbon to 50%, so you can still see both the ribbon & the table)

I should find some time in the next two weeks to have the evidence codes global (outside of the table, and filtering also all the ribbons)

**Comment by hattrill** [comment]
No problem @lpalbou - it's a busy time! Sounds great.

**Comment by srengel** [comment]
I love it.  I think it’s all looking great.
